#!/bin/bash

finished () {
  echo >&2 "$@"
  exit 0
}

list=($(cower -qu))
if [[ ${#list[@]} -eq 0 ]]; then
  finished "AUR packages are up to date."
fi

curpath=$(pwd)

for pkg in ${list[*]}; do
  if [ ! -d /tmp/$pkg ]; then
    cower --target=/tmp/ --color='auto' -d $pkg
  fi
  cd /tmp/$pkg
  makepkg -si
done

cd $curpath

finished "AUR packages have been updated."

