#!/bin/bash

die () {
  echo >&2 "$@"
  exit 1
}

if [ $# -eq 0 ]; then
  die "at least 1 argument required"
fi

curpath=$(pwd)

for pkg in $*; do
  if [ ! -d /tmp/$pkg ]; then
    cower --target=/tmp/ --color='auto' -d $pkg
  fi
  cd /tmp/$pkg
  makepkg -si
done

cd $curpath

